# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""
new fields filename, name_with_date  for report_schedule

Revision ID: 868884e3d5cd
Revises: 4ea966691069
Create Date: 2023-07-27 03:25:07.667332

"""
# revision identifiers, used by Alembic.
revision = '868884e3d5cd'
down_revision = '4ea966691069'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic
    op.add_column('report_schedule', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('report_schedule', sa.Column('name_with_date', sa.Boolean(), nullable=True))


def downgrade():
    # commands auto generated by Alembic
    op.drop_column('report_schedule', 'name_with_date')
    op.drop_column('report_schedule', 'filename')
